name: Checks
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run checks